# Generated by Django 2.1.1 on 2018-09-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180913_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='loctation',
            new_name='loctation_notice',
        ),
    ]
