# Generated by Django 2.1.1 on 2018-09-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180913_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='loctation_notice',
            new_name='lactation_notice',
        ),
    ]
