# Generated by Django 2.1.1 on 2018-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180913_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='cookbook',
            field=models.TextField(blank=True, null=True),
        ),
    ]
