# Generated by Django 2.1.1 on 2018-09-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180913_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='baby_comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='lactation_comment',
            field=models.TextField(),
        ),
    ]
